$ANSIBLE_VAULT;1.1;AES256
38323465366464386238313933636362343265623638636438663866623838373030373265343361
3235653266626430326666633463306665326237346339310a303963353832663564343530346265
35643263666465393062346138323232633333333931353130343531303364613433316538323131
6662326666303836640a376464613838356438633233396566643264616538613333643064343634
33366536303836633631303133626665663439633338346139643162653032323536643633323566
37323931356438626231363732633561376135663463303834343462663739303730363330626335
66373336313063363865393634353662336265363438613138353335383237396635646638653766
37373638396661393661653435336361326663343565386437653065366432356562386230393765
63663031636333613133666537343431313863326437306562653634306635363732653636356461
32643139333466333134623436616435613361373661313661336334663563653938366336363765
64633830393833326564313863393264356430363961323465386135383662653137373365336432
62643337366535376233366137363734656161613836343566636265616139343865393565653031
32636462613638303330313265313135626662393031343935363961653732383963613833636437
33656461633537353863663864346664613262613466633335346537653831306561353466396436
63616561663937663537616338323032633962363564356561373032373033363130336366396330
33306630616635616137326264333434313338393138663633346638323932396565633834346335
30333634306533386232323430386661636563656665646336633035326336366135
