$ANSIBLE_VAULT;1.1;AES256
31643035333739633863363230333434643961333332323238313366336661386439306161323835
3531666332313634356137326163363163613935346564300a333063323834656330353839656637
39623332656634373337646263333130356336303935316361383762616131303665666139343139
3536623666613837660a336532313938613863333261363930393765303733643537373530663833
34393039323230626533363331646139373162356335646466656434373336316336373763393737
31626265336430373163656162653034336665633765656361333833313162306634643436313463
65353763346366626564343533623263333634396232656430336665633037303661333363636233
39653334303766633232643961376137633866303765393239336634643931616534303732313831
36326336336537353838303232623262366237633364366632333133303063376366643235333765
34623232343562313864386166333533366662306438383739383364616235343761363035346631
66393837323435376261636161613661303235373635326566396639663733336437666334323030
66666130643738356536
